
server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/order?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/data.sql

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      retries: 0
      buffer-memory: 40960
      batch-size: 4096

    consumer:
      group-id: consume-test
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100


